### PR TITLE
Added ignoreBuildCalls parameter to be able to ignore build method's additional method calls

### PR DESCRIPTION
**Pull request by icelija**
If the StateNotifier's constructor calls some method that will update the state it will interfere with the method being called directly in the actions callback of the test itself.

For example if in the StateNotifier we have a constructor and method we would like to test like below:
```  
class ExampleStateNotifier extends StateNotifier<ExampleState> {
  final ExampleRepository _recipeRepository;
  ExampleStateNotifier(this._exampleRepository)
      : super(const ExampleState.initial()) {
    loadExampleString();
  }

  Future<void> loadExampleString() async {
    state = const ExampleState.loading();
    final result = await _exampleRepository.loadExampleString();
    state = result.fold(
        (failure) => ExampleState.error(error: failure.failureMessage()),
        (data) => ExampleState.loaded(string: data.string ?? ''));
  }
}
```
Now if we want in the test to test `loadExampleString()` method, because `loadExampleString()` is also being called from the constructor we won't get expected states in the test, `ExampleState.loading()` and `ExampleState.loaded(string: string)`. By adding a short delay after `build()` method is called in the `testNotifier()` method, `loadExampleString()` call from the constructor will be ignored and then when testing `loadExampleString()` we will be able to get the exact states we are expecting. 

The proposed solution then is to add new attribute `ignoreBuildCalls` when instantiating stateNotifierTest class and adding a short delay (100 ms should be enough for testing with mock repository) after the `build()` method is being called.

If you see a different and perhaps better solution for the described problem, feel free to share it :)

Other similar solution that comes to my mind is to introduce just `afterBuild` optional Future callback that could be await executed after the `build()` call to maybe have a little bit more options in defining how long this delay should be. On the other hand `ignoreBuildCalls` attribute is maybe more clear how to use it but I would also like to hear your opinion on that.

Kind regards,
Ivan Celija

### CODE REVIEW

**Comment by icelija** [comment]
The solution for the described issue is not to have any method calls in the constructor of the notifier so this pull request can be closed then.

**Comment by danijel-tolj** [comment]
@icelija 2 changes have been added to accomodate to such scenarios. 
First is a breaking change. The seed parameter now expects an array to enable you to seed multiple states.
Second is the expectInitialState boolean, which will also record the latest assigned state when the StateNotifier was created.
It is done this way to prevent unexpected behavior in the testing library. However it is my opinion that unawaited Futures called from the constructor can cause head scratches in the long run. My opinion is that initial API calls and similar asynchronous methods shouldn't be triggered by themselves from the constructor, as the duty of the constructor is basically to instantiate the class itself and not to trigger any behavior, especially a hard to test one.

An example which covers your usecase could be as follows: 

```
void main() {
  stateNotifierTest<CounterStateNotifier, int>(
    'emits [5,6] when increment is called from the constructor',
    build: () => CounterStateNotifier(),
    actions: (_) async {
      await Future.delayed(const Duration(milliseconds: 200));
    },
    expect: () => const <int>[5, 6],
    expectInitialState: true,
  );
}

class CounterStateNotifier extends StateNotifier<int> {
  CounterStateNotifier() : super(0) {
    state = 5;
    Future.delayed(const Duration(milliseconds: 100), () {
      increment();
    });
  }

  void increment() {
    state = state + 1;
  }
}
```

Note the awaited Future in the actions method. It will wait for the unawaited Future from the constructor to call the increment method.


Hope this helps.
Sincerely,
Danijel

**Comment by icelija** [comment]
@danijel-tolj thanks for the reply and for your solution to this case. Are you going to make the changes you proposed and push them to the main branch along with the version bump?

**Comment by danijel-tolj** [comment]
Already bumped to version 0.0.9, as well as pushed to the main branch, so I'm closing the PR .

**Pull request closed without merging**
